### PR TITLE
Add whitelist to phpunit.xml.dist

### PR DESCRIPTION
**Pull request by jordisala1991**
This fixes coveralls

### CODE REVIEW

**Comment by jordisala1991** [comment]
Removed commit but keep content of commit, because if not, build is not triggered (if you want me to remove that change also, I can do it)

**Comment by jordisala1991** [comment]
Tagged as critical because it is blocking other PRs

**Comment by greg0ire** [comment]
> Removed commit but keep content of commit, because if not, build is not triggered (if you want me to remove that change also, I can do it)

I'd like you to remove the change also, but then we can't merge, can we?

**Comment by jordisala1991** [comment]
We can, just build will not trigger (we will see changes on the next PR)

**Comment by greg0ire** [comment]
Fine, then please remove it.

**Comment by jordisala1991** [comment]
Done

**Comment by greg0ire** [comment]
Looks like coveralls/coveralls is required… can't merge (it shouldn't be required BTW)

**Comment by greg0ire** [comment]
Maybe there is something more meaningful you can commit?

**Comment by greg0ire** [comment]
Wow… this repo is really, really small!

**Comment by jordisala1991** [comment]
Yes. I though we could even deprecate it because doctrine/dbal on `master` already have this feature implemented, but it is not on a release yet (https://github.com/sonata-project/sonata-doctrine-extensions/issues/1)

**Comment by greg0ire** [comment]
> This has been included into Doctrine 2.3

**Comment by greg0ire** [comment]
Anyway, the comment removal you did is fine I think, put it back, but with a good commit message please.

**Comment by jordisala1991** [comment]
I can only change one or 2 files. IMO the change I made is correct.

It is here: https://github.com/doctrine/dbal/blob/master/lib/Doctrine/DBAL/Types/JsonType.php
It is not here: https://github.com/doctrine/dbal/tree/v2.5.12/lib/Doctrine/DBAL/Types/JsonType.php

funny

**Comment by jordisala1991** [comment]
It's even on doctrine documentation: http://docs.doctrine-project.org/projects/doctrine-dbal/en/latest/reference/types.html#json

**Comment by greg0ire** [comment]
Go ahead and put your change back please, but put a meaningful commit message

**Comment by greg0ire** [comment]
Thanks @jordisala1991 !

**Pull request merged**
