### PR TITLE
Add SqlWalker to sort tuples with NULL values on Postgresql database

### PR DESCRIPTION
**Pull request by jerome-fix**

### CODE REVIEW

**Comment by Soullivaneuh** [comment]
@jerome-fix your fix has a lot of tabs. This is not allowed. Please revert it to spaces.

**Comment by Soullivaneuh** [comment]
And please rebase your PR.

**Comment by Soullivaneuh** [comment]
Seems you did something wrong on the rebase. :-)

**Comment by jerome-fix** [comment]
Yes ! 
Can you destroy it? I create a new PR?

**Pull request closed without merging**
