### PR TITLE
Add support for PHP 8

### PR DESCRIPTION
**Pull request by core23**
## Changelog

```markdown
### Added
- Added support for PHP 8
```

### CODE REVIEW

**Comment by core23** [comment]
Blocked by https://github.com/doctrine/phpcr-odm/pull/817

**Comment by VincentLanglet** [comment]
> Blocked by [doctrine/phpcr-odm#817](https://github.com/doctrine/phpcr-odm/pull/817)

A doctrineORM user shouldn't be blocked by the Phpcr support of PHP 8.
Shouldn't we skip test related to PHPCR if PhpVersion is >= 8 ?

**Comment by core23** [comment]
It's a dev dependency, so it could be okay. If doing this, we should keep an eye on this to remove the temporary fix.

**Comment by franmomu** [comment]
It's also blocked by the other persistence layers:
- https://github.com/doctrine/orm - release of 2.8
- https://github.com/doctrine/mongodb-odm/pull/2248

**Comment by VincentLanglet** [comment]
Closed in favor of https://github.com/sonata-project/sonata-doctrine-extensions/pull/284

We can keep running test with the 7.4.99 platform hack (for dev dependencies), and allow php8 in order to allow others sonata bundles running the ci without the 7.4.99 hack.

**Pull request closed without merging**
