### PR TITLE
DevKit updates for 1.x branch

### PR DESCRIPTION
**Pull request by SonataCI**

### CODE REVIEW

**Review by phansys — APPROVED** [review]

**Comment by VincentLanglet** [comment]
Do you have time to merge into master (and make release of 1.x) @phansys ?

**Comment by phansys** [comment]
Sure @VincentLanglet, I'll take this :+1:

**Comment by phansys** [comment]
>Do you have time to merge into master (and make release of 1.x) @phansys ?

It seems that there is no need for a release from `1.x`:
https://github.com/sonata-project/sonata-doctrine-extensions/compare/1.11.0...1.x

```
doctrine-extensions
===================


                                                                                                                        
 [WARNING] Release is not needed                                                                                        
```

**Comment by phansys** [comment]
@VincentLanglet, the merge between `1.x` and `master` has no conflicts.
```
$ git merge 1.x 
Auto-merging src/Model/BaseManager.php
Merge made by the 'recursive' strategy.
 .github/workflows/qa.yaml   |  8 ++++----
 .github/workflows/test.yaml |  2 +-
 .yamllint                   | 15 ++++++++++++---
 Makefile                    |  2 +-
 phpunit.xml.dist            |  3 ++-
 src/Model/BaseManager.php   |  2 ++
 6 files changed, 22 insertions(+), 10 deletions(-)
```
Do you need a manual merge in order to have the code updated before the automatic dev-kit merge?
Otherwise, I think we should let dev-kit to perform the merge.

**Comment by VincentLanglet** [comment]
For the release, https://github.com/sonata-project/sonata-doctrine-extensions/pull/306 shouldn't be described as pedantic, since it's needed to fix another sonata project build

**Pull request merged**
