### PR TITLE
DevKit updates for 1.x branch

### PR DESCRIPTION
**Pull request by SonataCI**

### CODE REVIEW

**Comment by greg0ire** [comment]
:thinking: I don't understand or reproduce the PHPStan failure…

**Comment by phansys** [comment]
IIUC, It says that the ignored errors configured at `parameters.ignoreErrors` are not reached:
https://github.com/sonata-project/sonata-doctrine-extensions/blob/9dfdb3c7314b9c221efe4f87b98312f39cb1848b/phpstan-baseline.neon#L1-L2

**Comment by greg0ire** [comment]
Yeah, that's what I don't understand…

**Comment by greg0ire** [comment]
Ah I reproduce it when I download the latest version

**Comment by greg0ire** [comment]
In fact I think this might be intended: https://github.com/phpstan/phpstan-src/commit/1605bb2cddf65139e886df9a62aa7fe9dcfd03eb

**Pull request merged**
